### ISSUE TITLE
[JakartaONE Naming Consistency]   Brainstorming

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#10]
Hey community, 

Is there a reason why the JakartaONE website lists the 2020 3 events on a different fashion?
The current naming doesn't help with the Jakarta EE Branding  nor scales. 

I recommend we establish t_he bare minimum naming rules_ to help the JakartaONE LiveStream branding scale and become a global event.

- JakartaONE Brazil 2020 --- country event- localized OK! :) 

- JakartaONE in English 2020. the current name **The JakartaONE 2020** implies favoritism & puts the event above the other 2 events.  That ought to be fixed, there is no superior event when thinking about the LiveStream of JakartaONEs. 

- JakartaONE in Spanish 2020 needs to be fixed to JakartaONE En Español 2020.  Lets own the language across to match the event. 

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/10731224/89460648-78457f80-d71f-11ea-99db-0424ee32a04a.png">

**Comment by melissajacobus** [comment]
Hi Amelia, I was just recently assigned this ticket and I appreciate the thought you put into this. I agree that there needs to be be standard way in which these events are titled and so every event is treated in the same fashion.

We need to talk to the marketing committee as a whole -- but to your point doing something like:

    JakartaONE Americas, listing the date and time it is taking place and the language it is being presented in and being consistent across all of the events is key. I can see how it would be confusing for the community in terms of how the events are currently listed.  
    This would be the same for events like JakartaOne Russia, JakartaOne Japan, Jakarta One Brazil, etc.  I have this noted and will bring it to the marketing committee and am putting this into the formalized document for the entire committee to see. Thank you!
