### ISSUE TITLE
[JakartaONE Committee]  Sponsorships ??? if any- transparency on why is needed

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#11]
two parts:

**Value for**  by the event or after
participants: committee, speakers, volunteer organizers... etc:

-  what do you dream to have so that maybe "speakers & volunteers" get to keep as a thankyou swag for their involvement on this event?

**value for ** before, through and after

- what does an ORG get if it chooses to support the event?

- does the ORG understands clearly how their money will serve the event to the last penny. ?

 **nice to have**

- JUGs are the most valuable supporters on any virtual event that is focused on Language

- as such, their partnership needs to be THANK publicity.  Either JakartaONE put into place a nice % of the budget to be equally distributed to the JUGs proactively behind the event by:

- providing swag ahead of time to wear during the event

- envisioning versions of virtual JUGs that have their very own a few minutes Community Gatherings that can be nicely added to JakartaONE live event.   etc

**Comment by melissajacobus** [comment]
Hi Amelia, looking at this ticket since it was just assigned to me. 
You bring up some great points.  We definitely need to make sure we do more for people that help support the event. Some things that work and are easily able to be "shipped" and "delivered" especially during pandemic times are something like ebooks. And, a public thank you is always needed as well.

**Comment by aeiras** [comment]
I appreciate this ticket is being noticed. 

IMO if we are not shining the light to those #ossDOERs, then there is no value on whatever we might push via the project social media. To thank and do so openly and as honest and simple candid as it is deemed deserve is the best way to grow and protect the rebranding of Java EE. 

With that note, I agree with you. Mailing stuff during this pandemic is bare to impossible. 
e-books and media pushes suffice. Safety must always be prioritized. :) 

Gracias Melissa!
