### ISSUE TITLE
[JakartaONE Committee] Q&A for the event - website

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#12]
using the current drive space- the most common Q&A you are discovering by doing need to be written under the document. 
- using the pull request under this space, that document can be added to the website to be adjusted as the community of #ossDOERs see fit in the future via PRs :) 

-- it is bothersome to realize something, to find its solution only to drop the ball on sharing / tracing such a valuable information that could teach others your findings but also enable others to pay closer attention on the importance on scaling our knowledge while doing stuff. Teaching matters, writing matters.

**Comment by melissajacobus** [comment]
I really like the idea of having Q&A from the events on the web.  I think this is definitely something that we should look into making available (along with reposting the slides from the event) on each of the event web pages. I will bring this up to the marketing committee.

**Comment by aeiras** [comment]
Hola Melissa, 

Thanks for helping tackle many of the tickets created in this Repo. I appreciate it. :)
