### ISSUE TITLE
[JakartaONE Committee]  Formalized Media pushes Messages

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#13]
It is the job of the committee to not only write formal messages that are sent by the individuals to the forums but also to write the media messages that are distributed via the formal Jakarta EE media channels, Twitter, FB etc. 

That work and its desired scheduled needs/ought to be submitted via git issues so that those behind the management of the JakartaONE media channels (100% the hired Jakarta EE individuals under the Marketing budget) clear it with the Marketing Committee, who are there to protect you and support you stand beside you as Facilitators.

**Comment by melissajacobus** [comment]
Hi Emelia, 
I'm sorry for the delay in our team getting back to you on your GitHub tickets. I have just recently been assigned a handful of yours.  You bring up so many wonderful points that I am taking your tickets and formalizing them in a document for the Jakarta EE marketing committee to refer to as we plan JakartaOne events, new launches/iterations of Jakarta EE, etc. I'm adding this to that document, so closing this ticket out. Please know, we will keep all of your suggestions in mind and refer to them as we plan activities moving forward. Thanks for all of your support!

**Comment by aeiras** [comment]
Glad to hear conversations will happen, Melissa!
