### ISSUE TITLE
[JakartaONE Committee]  Populating the JakartaONE wiki for the event under Projects

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#17]
using pull requests, most of the data found in the JakartaONE drive for the event needs to start populating the JakartaONE Español wiki. 

Make no mistake, the committee doesn't need to be a Jakarta EE committer to be able to help properly document such information. 

Ideally, every JakartaONE by country or continent will get its own dedicated Project, as seen below to make each iteration of the event better, directly via PRs. :) 

<img width="788" alt="image" src="https://user-images.githubusercontent.com/10731224/86986923-a8622880-c149-11ea-80e8-c6a0e30eba20.png">

**Comment by cesarhernandezgt** [comment]
@aeiras 
Currently, https://github.com/jakartaee/jakartaone.org is the repository for the jakartaone.org website.  
The repository is under the JakartaEE Github Organization.

If we enable the wiki on https://github.com/jakartaee/jakartaone.org, remember that GitHub doesn't support pull requests for the wiki section. 

The approach of creating peer Region (country) wiki documentation is currently being applied using [Google Drive](https://drive.google.com/drive/u/0/folders/1Wc1rdaDZeh2xhOfSPmAJAk_TrIveTeNx), and this doesn't require (as far as I know) a Jakarta EE committer status. This relates to https://github.com/jakartaee/collateral/issues/21

**Comment by aeiras** [comment]
How about pages, @cesarhernandezgt ? 
If wikis are not possible, pages might work better. 
Google drive is ok but it rarely scale to bring it to the Website.

**Comment by cesarhernandezgt** [comment]
@aeiras pages is already applied here by language basis: https://github.com/jakartaee/jakartaone.org/tree/master/content
I think that once the process gets migrated from pdf into github via https://github.com/jakartaee/jakartaone.org/issues/417, then we will be able to use githbub pull request workflow also for language-specific documentation (wiki as you call it)

**Comment by aeiras** [comment]
I am really excited about that PR that converts the PDF guidelines, Cesar. 
Great job on the diverse items on this update. :)

**Comment by cesarhernandezgt** [comment]
@aeiras, I'm closing this now that https://github.com/jakartaee/jakartaone.org/issues/417 was already merged and PR are available to improve the existing documentation.

**Comment by aeiras** [comment]
Thank you, Cesar!
