### ISSUE TITLE
[JakartaONE Committee]  Message to the Jakarta EE Spanish Community introducing the event

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#20]
Ideally the message is written by the Committee in Spanish and signed as- the JakartaONE Committee Team on all messages that are formal and are aimed to represent the event. 

Using the drive, this and similar templates ought  to be hosted. 

Call to Action to support by becoming a speaker, a sponsor, a watcher of the event matters. THAT message must provide an insight of the project, which includes its skeleton, even if only draft-- it is important.

**Comment by cesarhernandezgt** [comment]
Base on @HillmerCh message on July 22nd 2020. It seems this ticket can be close now.
Feel free to open it if that is not the case.
