### ISSUE TITLE
[JakartaONE Committee] JakartaONE Español folder in the CommunityDrive

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#21]
https://drive.google.com/drive/u/0/folders/1sRSywb22ioT98uRVKK0sBU8MiMWzFY_n

The Committee needs to gain write access to manage this space. 
Recommendations:

- edit access to each member of the Committee

- Current skeleton needs to be translated and adjusted as the Committee accomplish stuff into Spanish

- Folders:

1. Design to contain: media general pushes, speakers slides, design cards for speakers, etc
2. Blogs:  content written by the Committee who pushes such information to the Jakarta EE ecosystem- in Spanish
3. Skeleton of the event
4. Q&A about the event that will be imported to the JakartaONE website 
etc

**Comment by cesarhernandezgt** [comment]
This ticket applies to the overall internal process Eclipse Foundation needs to manage all the events.
I think this ticket can be closed since now we the https://jakartaone.org/documents/jakartaone-language-host-process.pdf document states the Google Drive access to Committee members:

> A specific folder in the Community Folder so the progress is transparent for everyone.

**Comment by aeiras** [comment]
Spot on @cesarhernandezgt!
