### ISSUE TITLE
[Friends of Jakarta EE video recorded] Submitted to be added to the Youtube channel under Friends of Jakarta EE

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#25]
Ivar, 

Can you please grant me the access to drop today's recording into the Friends of Jakarta EE folder? Thanks

https://drive.google.com/drive/u/0/folders/1rbf7GMwZRtplOICVSJoPpBXY__awudWP

**Comment by cesarhernandezgt** [comment]
@aeiras the folder on this ticket doesn't contain any video.
Was this solved on #55  ? If yes, feel free to close the issue. 
If not, please provide the link to the video.

**Comment by aeiras** [comment]
Cesar here are the recordings https://drive.google.com/drive/u/0/folders/1lMycb_sdEt7YWbwn1_-xQNIVyxy4XLt9

**Comment by cesarhernandezgt** [comment]
@aeiras Thak youf for the link.
Both videos seems to be already uploaded via: https://github.com/jakartaee/collateral/issues/55
https://www.youtube.com/watch?v=EbzTBH9Gn9U&feature=youtu.be
https://www.youtube.com/watch?v=llKo4kUzRwQ&feature=youtu.be

Feel free to close the ticket if this is accurate or point to the correct videos you want to upload.

**Comment by aeiras** [comment]
perfect! thanks Cesar
