### ISSUE TITLE
[JakartaONE Speaker Slides]  Contribution by Tomitribe

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#31]
Hola Jakarta EE Community, 

[JakartaONE Speaker Slides](https://docs.google.com/presentation/d/1B2X-y5qm0VJa6QO9WACID0dat52iXQGmjInEZqBIDg0/edit#slide=id.g93424bc438_3_432)

While contributing to the JakartaONE en Español event, we have created the speaker slides. 
Please not that the presentations are scalable in usage and could be a version used by future JakartaONEs. 

Currently the slides are located in the Jakarta Community Drive under > Photos.
Ideally, they are moved to the JakartaONE folder under Speakers' Resources folder. 

It is always our pleasure to contribute to activities that enable anyone within the ecosystem to help him/herself by doing stuff!

**Comment by TanjaObradovic** [comment]
I just replied to this this in https://github.com/jakartaee/jakartaone.org/issues/209. But pasting here as well

For each of the regional or language specific virtual conference we have a folder in the Community Folder -> JakartaOne Livestream - Spanish
https://drive.google.com/drive/u/0/folders/1sRSywb22ioT98uRVKK0sBU8MiMWzFY_n
I believe we can us that folder for the template presentation. I am not sure we need to put the link on the website, particularly now that the conference is done. If the community decides to organize the conference again next year, we may want to update the template, and ensure the Program Committee provides the template to speakers a few weeks prior the event.

**Comment by melissajacobus** [comment]
Wanted to circle back on this since I was just assigned the ticket. I agree that having a repository that people can access from the web with slides, etc. from each event is a good idea. I do think we should leave the slides up on those pages somewhere for folks to access until we run that event again. I will share this with the Marketing committee. Having references (even just PDFs) of the slides/content presented is extremely valuable IMO.

**Comment by aeiras** [comment]
Melissa, 

I will show you an example of how we enable the MicroProfile community via the project website created and continues to improve (based on users' feedback) its Branding page. 
I have stated years of feedback on making the Jakarta EE website the project's source of truth. That includes its JakartaONE website as well. 

[MicroProfile Branding Page- Example](https://microprofile.io/resources/branding/)

MicroProfilers run the MP website 100%. It is easier to test any recommendations and, based on usage, adjust stuff. 

Ideally, Jakarta EE becomes a more low bar to entry into acquiring and acknowledging its community feedback so that improvements do not take months. 

Cheers,
