### ISSUE TITLE
Initialization on repo for Git LFS seems to be need it

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/collateral#33]
Currently, a contributor can´t push to collateral github forks LFS content since the upstream repo doesn´t have any LFS content. This prevents one to be able to create a Pull Request to jakartaee/collateral

The error I got locally when trying to push to an existing PR any LFS content is:

```
git push
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
batch response: @cesarhernandezgt can not upload new objects to public fork cesarhernandezgt/collateral
```

Proposed steps to solve this issue:

1. Add .gitattributes to the collateral repository, I already opened a PR for this: https://github.com/jakartaee/collateral/pull/32

2. A repository committer needs to push one .mp4 file (I'm attaching one on this issue [videotest.mp4.zip](https://github.com/jakartaee/collateral/files/5357682/videotest.mp4.zip)) into `collateral/video/community-content` folder.

Background information related to this issue: 
https://github.com/benmiller314/cdm2019fall/issues/9
https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273

**Comment by cesarhernandezgt** [comment]
Hi @eclipsewebmaster  @ivargrimstad 

Until https://bugs.eclipse.org/bugs/show_bug.cgi?id=567494 gets resolved, I think you are the only ones at this point who can help on this one. Any help will be appreciated 👍

**Comment by ivargrimstad** [comment]
Pinged the bug...

**Comment by cesarhernandezgt** [comment]
Closed this one since GLF is working now.
