### ISSUE TITLE
【Question】: I want to join JakartaEE Working Group, but do I have to join Eclipse Foundation Member first?

### ISSUE THREAD

**Issue by zhengshundong01** [jakartaee/collateral#34]
i have read https://jakarta.ee/documents/membership/jakarta-ee-membership-prospectus.pdf

this pdf say：
learn how to become a member on this page：https://www.eclipse.org/membership/become_a_member/

i have see this page is Eclipse Foundation member，so i need join this first ?

**Comment by cesarhernandezgt** [comment]
@zhengshundong01 
I'm closing this issue base on the above answer Tanja and Ed provided, feel free to reopen or open a new issue if further questions arise.
As a complementary note, this is generally the process we document to collaborate in Collateral or any other Jakarta EE repository: 
https://github.com/jakartaee/collateral/blob/master/CONTRIBUTING.adoc
