### ISSUE TITLE
Webtide Submission of Participant Quote

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jakartaee/collateral#39]
The Jakarta EE project represents a noble goal of free and open-source development on the Java specifications that are absolutely core to the Java experience.  The Eclipse Jetty project and its developers at Webtide have contributed to many of these specifications since their inception and are pleased to continue doing so as a part of Jakarta EE.

Jesse McConnell - CEO - Webtide

**Comment by aeiras** [comment]
Beautiful Jesse! :) abrazos
