### ISSUE TITLE
[Youtube][Swag Request] Swag request for Youtube show

### ISSUE THREAD

**Issue by mkarg** [jakartaee/collateral#40]
*Related to this ticket [[JakartaONE Champions Program- THANK YOU] Swag request for Committee & Speakers #221](https://github.com/jakartaee/jakartaone.org/issues/221)*

I will be the host of a live show on my Youtube channel on November 20th at 20 CET where I will host Ivar Grimstad livehacking on some code. This is an innofficial fun coding show about Jakarta EE 9. Can you please send some merch props we can use on that show?

**Comment by trulymobilenwp** [comment]
Event concluded. Need to determine SWAG strategy when digital events.
