### ISSUE TITLE
 [Jelastic] Submission of Jakarta EE Working Group Participant Quote

### ISSUE THREAD

**Issue by TetianaFTV** [jakartaee/collateral#41]
Quote:
**"Jelastic team keeps working tightly with Jakarta EE ecosystem to make this technology cloud-friendly, scalable and easily available for developers worldwide. Jakarta EE project is constantly introducing new improvements and we are committed to instantly spread these updates via our PaaS deployed across network of service providers to meet the needs of Java community in tune with the times."**

Author: **Ruslan Synytsky, CEO and co-founder of Jelastic**

Twitter: https://twitter.com/siruslan

Photo:
![RS](https://user-images.githubusercontent.com/38689227/98756245-72200880-23ca-11eb-9068-8f8e2886eac2.jpg)

**Comment by aeiras** [comment]
wonderful Tetiana! : )

**Comment by cesarhernandezgt** [comment]
@TetianaFTV Can you please expand the context of this ticket?
News on the website has been self-service:  https://newsroom.eclipse.org/node/add/news but we wonder if this is the scope of quote you provided.

**Comment by TetianaFTV** [comment]
@cesarhernandezgt 
It is not news or article, it is a quotation for the website carousel of quotes.
This ticket was created based on Amelia's request in the following thread "[jakarta.ee-wg] [Jakarta EE Participant Members Quotes] NEEDED" in October.

Here is a short part with explanation from that email:

"I sent to the new Marketing repository issue [[Participant Members Quotes] ought to be added to the Membership rotation #30](https://github.com/jakartaee/collateral/issues/30)

This is a voluntary submit your quotes (applicable to 11 Members, including Enterprise) answering in 2 to 3 sentences via the Issue ticket, why you choose to support/invest your ORGs' money, human capital resources & time to the re-branding of Java EE. 

Currently, the quotes that rotate in the [Membership Benefits](https://jakarta.ee/membership/#benefits
) page have only 6 quotes from Strategic Members. "

Anyway, I still don't see this quotation published on the mentioned page even after ticket creation, so not sure if it went anywhere at all.

**Comment by cesarhernandezgt** [comment]
Thank you for the context @TetianaFTV 
I created a new issue in the https://github.com/jakartaee/jakarta.ee/issues/1098 jakarta.ee repository along with a PR because the change to add a quote is pretty straightforward in the code. 
Feel free to close this issue so any follow-up can be handled in the jakarta.ee repository and the corresponding issue.

**Comment by TetianaFTV** [comment]
sure, thanks @cesarhernandezgt!
