### ISSUE TITLE
[Youtube Playlist Creation]   Jakarta EE TCK Playlist

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#48]
Hey team, 

We have submitted +5 recordings from the zoom recorded calls which started in September to this space. 

Can you please create the Jakarta EE TCK Playlist and start processing the submitted video content contributions? 

Thank YOU!

**Comment by hudsonkelly83** [comment]
@aeiras playlist created: https://www.youtube.com/playlist?list=PLutlXcN4EAwCgj3v4WQSQR66_uOjoNBeg

I was only able to find two videos - one from Sept 4 and the other from Oct 9 - If you could please point me to the other three I will gladly add them.

**Comment by aeiras** [comment]
Thank you Kelly for creating the TCK playlist. 

@cesarhernandezgt submitted a few of the TCK videos via PR while I submitted others via issues. Stand by and thanks for  pushing the content to the Youtube channel, very happy!

**Comment by aeiras** [comment]
@cesarhernandezgt, 

 I still don't know the video contributing process, can you point me to the documentation? Thanks

**Comment by cesarhernandezgt** [comment]
@aeiras 
This is the main contribution document: https://github.com/jakartaee/collateral/blob/master/CONTRIBUTING.adoc
In that document, you will find the video specific guidelines.
As for the required information to add in the specific github issues, we are working to have issue templates specific for content type.

**Comment by cesarhernandezgt** [comment]
A proposed example was done here: https://github.com/jakartaee/collateral/issues/5 
I'll create a PR for this issue template.

**Comment by aeiras** [comment]
Cesar, 

I was going to recommend examples, but you gotcha. :) 
 The document has improved wonderfully Cesar. Thank you for sharing it.  

Do you want to send it off to the Community forum? 
It is such an important enabling document. It doesn't have to be perfect to reach our ecosystem and welcome the many videos and more contributions currently available!  If you need help, happy to support you. Just pull me in. Lets do this! 

let me know and thanks for dedicating much care to shape the contributing process.

**Comment by aeiras** [comment]
Closing this issue. Thanks Cesar and Hudson!
