### ISSUE TITLE
[Youtube video contribution] Jakarta EE TCK demo:  2020-11-13 Recording_Running The Platform TCK Demo with making test change

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#49]
Please use the **video title** below when importing the video to the play list:

[2020-11-13 Recording_Running The Platform TCK Demo with making test change](https://drive.google.com/drive/u/0/folders/1CgikCM-UcAhFOps63-ulEEZ7im7LB7MN)

Thank you,

**Comment by cesarhernandezgt** [comment]
@aeiras @hudsonkelly83 
I opened a PR to solve this ticker: https://github.com/jakartaee/collateral/pull/53

For consistency purposes with the previous recording that is now available on the youtube channel, I suggest using the following information for the youtube Title and description:


**Jakarta EE TCK Community Outreach Call Nov 13, 2020**

Video Title: Jakarta EE TCK Community Outreach Call Nov 13, 2020

Youtube playlist: 
Jakarta EE TCK

Description:
This call welcomes everyone interested in join and contributes to Jakarta EE TCK.
The call provided a hands-on demo on setting up locally and running the Jakarta EE Platform TCK, along with the current project status and documentation.

► Project website with links to the repository and the jakartaee-tck-dev mailing list: https://projects.eclipse.org/projects/ee4j.jakartaee-tck/developer

Find out more about Jakarta EE and follow:

Website: https://jakarta.ee
Twitter: https://twitter.com/JakartaEE
Facebook: https://www.facebook.com/JakartaEE
Linkedin: https://www.linkedin.com/groups/13597511/

**Comment by aeiras** [comment]
I didn't know videos could accept short descriptions, if YES, your recommendation rocks! + 1 of scaling the TCK video recording contributions to your recommendation Cesar!

@hudsonkelly83 thank you for your time on this!

**Comment by hudsonkelly83** [comment]
Done! https://youtu.be/QI229N1aAEw

**Comment by cesarhernandezgt** [comment]
Thank you @hudsonkelly83 . I'm going to merge https://github.com/jakartaee/collateral/pull/53.
