### ISSUE TITLE
[technical talk video] Jakarta EE TCK Community Outreach 2020-09-04 and 2020-10-09

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/collateral#5]
**Jakarta EE TCK Community Outreach Call Sep 4, 2020**

**Video Title**: Jakarta EE TCK Community Outreach Call Sep 4, 2020

**Youtube playlist**:
~~ [Community Content](https://www.youtube.com/playlist?list=PLutlXcN4EAwCefsYB_Cqw4IXY2VDc--fh)~~
It seems a specific "Jakarta EE TCK" Playlist youtube playlist was already mentioned on https://github.com/jakartaee/collateral/issues/48 so I updated the original proposed playlist.

**Description**: 
This call welcomes everyone interested in join and contributes to Jakarta EE TCK.
The call provided visibility on the current status of the Jakarta EE TCK toward Jakarta EE 9 release and beyond, along with how the community is striving for documentation restructure to simplifies new contributors to join the project. 

► Project website with links to the repository and the jakartaee-tck-dev mailing list: https://projects.eclipse.org/projects/ee4j.jakartaee-tck/developer

Find out more about Jakarta EE and follow:

Website: https://jakarta.ee
Twitter: https://twitter.com/JakartaEE
Facebook: https://www.facebook.com/JakartaEE
Linkedin: https://www.linkedin.com/groups/13597511/

------------------------------

**Jakarta EE TCK Community Outreach Call Oct 9, 2020**

**Video Title**: Jakarta EE TCK Community Outreach Call Oct 9, 2020

**Youtube playlist**:
~~ [Community Content](https://www.youtube.com/playlist?list=PLutlXcN4EAwCefsYB_Cqw4IXY2VDc--fh)~~
It seems a specific "Jakarta EE TCK" Playlist youtube playlist was already mentioned on https://github.com/jakartaee/collateral/issues/48 so I updated the originally proposed playlist.

**Description**: 
This call welcomes everyone interested in join and contributes to Jakarta EE TCK.
The call provided two live code demos showing how to run a set of tests and also how standalone TCKs already migrated the TCK architecture from JT Harness into arquillian and JUnit.

► Project website with links to the repository and the jakartaee-tck-dev mailing list: https://projects.eclipse.org/projects/ee4j.jakartaee-tck/developer

Find out more about Jakarta EE and follow:

Website: https://jakarta.ee
Twitter: https://twitter.com/JakartaEE
Facebook: https://www.facebook.com/JakartaEE
Linkedin: https://www.linkedin.com/groups/13597511/

**Comment by cesarhernandezgt** [comment]
This Issue and the corresponding PR is blocked by https://github.com/jakartaee/collateral/issues/6

**Comment by cesarhernandezgt** [comment]
This issue and corresponding PR is blocked now by https://github.com/jakartaee/collateral/issues/33

**Comment by hudsonkelly83** [comment]
Videos posted to the TCK Playlist: https://www.youtube.com/playlist?list=PLutlXcN4EAwCgj3v4WQSQR66_uOjoNBeg

Apologies for the delay.

**Comment by cesarhernandezgt** [comment]
Thank you @hudsonkelly83 .
I'll merge the corresponding PR https://github.com/jakartaee/collateral/pull/52 and close this issue.
