### ISSUE TITLE
[Jakarta EE Playlist Request] for Friends of Jakarta Recordings

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#55]
Can the Friends of Jakarta EE playlist be created?

2 videos are awaiting to be exported to the medium:

- [[Friends of Jakarta EE Call Recording] October 28th Video](https://github.com/jakartaee/collateral/issues/37)

- [[Friends of Jakarta EE Call Recording] September Video](https://github.com/jakartaee/collateral/issues/25)

**Comment by hudsonkelly83** [comment]
@aeiras the playlist is created: https://www.youtube.com/playlist?list=PLutlXcN4EAwB5vLXOawBkqLTFclGSeF7P

I was able to add the sept 23 meeting (https://youtu.be/EbzTBH9Gn9U) but I was not able to convert the zoom file for the October 28 meeting. If you could please convert that video to an mp4 file and re-upload it, I can put it on YouTube. 

Thank you!

**Comment by aeiras** [comment]
Thank you Hudson for creating the playlist, really appreciated that!

I will look into the video issue and hopefully fix it for export.

**Comment by cesarhernandezgt** [comment]
@hudsonkelly83 I found the correct link for the recording of the call from October 28th: 
https://drive.google.com/drive/u/0/folders/1wsPC8p_E3bpN7D5TA7eU1A1h2uJewaka 
checkout the file in mp4 seems to be already available under the name: `zoom_0.mp4`

**Comment by hudsonkelly83** [comment]
@cesarhernandezgt Great thank you! I've uploaded the video here: https://youtu.be/llKo4kUzRwQ and added to the Friends of Jakarta EE playlist

**Comment by cesarhernandezgt** [comment]
Thank you @hudsonkelly83 .
@aeiras I'm closing this issue now that it has been resolved.
