### ISSUE TITLE
Request to enable Git LFS in this repository

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/collateral#6]
Can some of the repository administrators please enable Git LFS to this repository.

The setting is at  https://github.com/jakartaee/collateral/settings  under the `Archives` section with the checkbox `Include Git LFS objects in archives`

**Comment by TanjaObradovic** [comment]
Can someone help with this? I am not sure what need to be done here :)

**Comment by eclipsewebmaster** [comment]
Done.
