### ISSUE TITLE
[ jChampions Conference 2021] - Paving the way with Jakarta EE and Apache TomEE

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/collateral#60]
@hudsonkelly83 
It seems @JakartaEE haven't been notified but this week the jChampions Conference 2021 is going to take place for the first time. A lot of Jakarta EE will be part of the agenda. The following are the details of the session I'm going to deliver in case there is still a chance to promote or at least retweet my and the rest of the sessions related to Jakarta EE.

Conference Name: The jChampions ConferenceConference website: https://jchampionsconf.com/

Conference social media links: https://twitter.com/JChampionsConf

Title: Paving the way with Jakarta EE and Apache TomEE

Date and hour:  Thursday, January 14 2021 @ 10:00 AM EST

Speaker name: Cesar Hernandez Speaker twitter handle: @CesarHgt

Tweet messages (max: 200 characters): 

Twitter message

Join @CesarHgt at @JChampionsConf on Jan 14 at 10 am EST and check how easy is to migrate to the latest release of Jakarta EE. Free Registration  https://jchampionsconf.com/ #TomEE #OpenSource @ApacheTomEE @JakartaEE @java_champions

**Comment by hudsonkelly83** [comment]
Hi @cesarhernandezgt I can definitely get some promotion for you, we will retweet your content and send out our own an hour before your session.

**Comment by cesarhernandezgt** [comment]
thanks, much @hudsonkelly83 and team for the support.
https://twitter.com/JakartaEE/status/1349720278411202561

Closing now this issue.
