### ISSUE TITLE
[Community Blog] Marketing Coverage

### ISSUE THREAD

**Issue by WalkerWatch** [jakartaee/collateral#61]
Together with a number of contributors and projects, a blog was put together highlighting efforts to integrate and bring EE9 into the community. Would love for it to get some Branding coverage from the Marketing space. The blog is below. Additionally, I've requested for Webtide Jakarta blogs to be added to the [JakartaEE blogs](https://jakartablogs.ee/#main-content) page in [a separate issue](https://github.com/jakartaee/jakartablogs.ee/issues/89).

Blog: https://webtide.com/community-projects-contributors-take-on-jakarta-ee-9/

**Comment by cesarhernandezgt** [comment]
Hi @WalkerWatch ,
Thank you for submitting the blog post. 

Hi @hudsonkelly83 , after this blog post feed is added to JakartaEE blogs via the already created [issue](https://github.com/jakartaee/jakartablogs.ee/issues/89), who should we contact or assign this ticket to have JakartaEE social media diffusion?

**Comment by hudsonkelly83** [comment]
Hi @cesarhernandezgt , @WalkerWatch , I can promote it across Jakarta EE socials starting tomorrow.

**Comment by cesarhernandezgt** [comment]
Thank you all for the work done in this ticket. https://twitter.com/JakartaEE/status/1349353507464294401
