### ISSUE TITLE
Friends of Jakarta Video Call Jan 27 2021

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/collateral#62]
Hi, the following is the information need it to upload the past call recording. I'll open a PR containing the video since Github Issues doesn't allow attachments larger than 10 MB.

Video Title: Friends of Jakarta EE | Jan 27, 2021

Youtube playlist: Friends of Jakarta EE

Description:
This call welcomes everyone interested in join, share and learns about Jakarta EE.

Find out more about Jakarta EE and follow:

Website: https://jakarta.ee
Twitter: https://twitter.com/JakartaEE
Facebook: https://www.facebook.com/JakartaEE
Linkedin: https://www.linkedin.com/groups/13597511/

**Comment by hudsonkelly83** [comment]
Video uploaded to Jakarta EE YouTube https://youtu.be/oCfrMSQKWn4

**Comment by cesarhernandezgt** [comment]
Thanks @hudsonkelly83 !
