### ISSUE TITLE
Please add Melissa as collateral committer

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/collateral#65]
Currently, Melissa Jacobus GitHub username @melissajacobus can't be added as an assignee for issues in this repository.
Can one of the repo admins please add Melissa as a committer for this repository?
cc: @ivargrimstad @TanjaObradovic 

![image](https://user-images.githubusercontent.com/1454523/111824220-878ecd00-88ab-11eb-94b4-d91a62414135.png)

**Comment by TanjaObradovic** [comment]
Quick update internally are looking to add @melissajacobus to the contributor group.

**Comment by chrisguindon** [comment]
I sent an invitation to https://github.com/melissajacobus to become a member of the collateral-committers team!

**Comment by TanjaObradovic** [comment]
thanks @chrisguindon! 

@melissajacobus once you are all set, please close this issue. Thanks!

**Comment by melissajacobus** [comment]
Thanks @cesarhernandezgt and @chrisguindon
