### ISSUE TITLE
[Jakarta EE Platform call Media Push] Weekly reminders via the Jakarta Handle

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#66]
Right now I am attending (rare) the 8am-9am PDT call. 
Can the team create and push weekly ~5hrs before the call the calendar link with  a short summary of the call value to bring awareness of it? 

Tweet [here ](https://twitter.com/ameliaeiras/status/1374380364550922241?s=20)as an example of pushing awareness of this important call. 

Thank you, Tanja!

**Comment by jph152** [comment]
Hi Amelia, we can start posting reminders for these calls early Tuesday morning EDT.

**Comment by TanjaObradovic** [comment]
Thanks @jph152 and @aeiras. I propose we close this issue and re-open if there is a need for it. If OK @aeiras please close the issue or let me know if you agree and I will.

**Comment by aeiras** [comment]
I think it is wonderful. Thank you! 💙
