### ISSUE TITLE
[Remembering our Fallen Jakartees] Via Jakarta EE Twitter media

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#7]
I have been thinking for awhile, after we- the Jakarta EE project lost Bill Shannon early this year. 

If there a way for the Marketing team to design a card and a message directed to Bill's family and the entire community where we acknowledge how deeply missed he is and how important he was for Jakarta EE since its onboarding and for that matter since Java EE was created?

**Comment by aeiras** [comment]
@chrisguindon,

I just saw the Memorial page via email arrive in my inbox. It is a good start. Many thanks

**Comment by chrisguindon** [comment]
YW

Here's a direct link if someone is looking for the URL: https://gitlab.eclipse.org/eclipsefdn/memorials/

**Comment by TanjaObradovic** [comment]
This has also been addressed awhile back so closing the issue.
Thanks!
