### ISSUE TITLE
[Jakarta EE session] JConf Peru 2021

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/collateral#76]
Hi @HailleySeed 

I'm going to provide a JakartaEE related session next Saturday in a event organized by the Peru JUG, It would be great if community-driven sessions can be socialized via Jakarta EE social media in the same way contribution from the community has been amplified before [1].

Details of my session:

- Conference Name:  JConf Peru 2021
- Conference website and social media links:   https://jconf.perujug.org/ and https://twitter.com/perujug
- Videos: Youtube:https://www.youtube.com/watch?v=nSIUpdKTpfU  Facebook:https://www.facebook.com/groups/perujug/permalink/3058547247735363/
- Title: 7 recommendations to migrate your Java Enterprise application into Jakarta EE with TomEE
- Date and hour: Saturday November 27th 12:00 PM GMT-5

[1]
https://twitter.com/JakartaEE/status/1435259227149381640
https://twitter.com/JakartaEE/status/1427984503516114948

**Comment by HailleySeed** [comment]
Hi @cesarhernandezgt 

Yes absolutely!

 Do you have a date you would like this to go out on?

Thanks!

**Comment by cesarhernandezgt** [comment]
> Hi @cesarhernandezgt
> 
> Yes absolutely!
> 
> Do you have a date you would like this to go out on? Does tomorrow, the 25th work?
> 
> Thanks!

Yes, tomorrow 25th works just fine. 
Thank you!

**Comment by cesarhernandezgt** [comment]
Closing this and thank you again for the support https://twitter.com/JakartaEE/status/1463948339746119682
