### ISSUE TITLE
[Update the Jakarta Mktg Slack guests] 2020 WG 

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#8]
Hola Jakarta Mktg team, 

Given that 2020 Jakarta EE elections are concluded and across the board the onboarding has been completed, can the Slack private channels be updated as  part of the yearly onboarding process?  Using slack as an example, all tools that enable private collaboration under this project need to be audited to match Contributors' current and past status.  

Slack collaboration is not for everyone, yet it matters that the space (currently holding 29 individuals)  and anything WG private & related to the active collaboration be mirrored with care. 

I count 6 guests that need to be removed from mktg slack. Thank you!

**Comment by TanjaObradovic** [comment]
I just realized this ticket is still open. This has been addressed awhile back and I am closing this ticket.
Thanks!
