### ISSUE TITLE
[Migrating from Java EE to Jakarta EE 9] OSS Ecosystems that are preparing to Migrate need highlight

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#9]
5/13- Sent via the Jkta Mktg slack #general channel with respect to ask the WG in the branding side to  initiate the prioritizing of any OSS ecosystems that are proactively starting to prepare their users to move to Jakarta from Java EE. The change is required given the name space change with Jakarta EE 9 release. 

Msg below and exact link using Apache Tomcat as a fantastic example tweet [HERE](https://twitter.com/TheApacheTomcat/status/1260530953648250880?s=20)

<img width="838" alt="image" src="https://user-images.githubusercontent.com/10731224/81842267-93c63300-9500-11ea-84a0-3b984aa94f4a.png">

**Comment by TanjaObradovic** [comment]
Thanks Amelia, this is on-going effort. So no reason to have the issue open any longer.
